version: "3.7"
services:
  mongodb:
    # This image automatically creates a replica set required for transactions
    image: mongo
    container_name: ct_mongo
    restart: always
    networks:
      - yufix_network
    volumes:
      - ./db:/data/db
    #environment:
    #MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
    ##MONGO_INITDB_DATABASE: ${MONGO_DB}
    #INIT_WAIT_SEC: 3
    ports:
      - 27017:27017

networks:
  yufix_network:
    driver: bridge
